### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by endavainterns2016** [croitor-ivan/CacheableObserver#2]
Application crashes on 

`final List<EventContext> observerKeys = next.getObserverKeys();`

in Subject.java if class that implements Observer interface returns null in getObserverKeys() method.

**Comment by croitor-ivan** [comment]
Fixed with 
https://github.com/croitor-ivan/CacheableObserver/pull/4

**Comment by croitor-ivan** [comment]
Fixed with #4
